# Generated by Django 5.0 on 2023-12-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=50)),
                ('nombre_tratamiento', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha', models.CharField(max_length=12)),
            ],
        ),
    ]
