# Generated by Django 5.0 on 2023-12-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estetica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='nombre_paciente',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='nombre_tratamiento',
            new_name='tratamiento',
        ),
    ]
