# Generated by Django 4.2.7 on 2023-12-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_tratamiento",
                    models.CharField(default="tratamiento x", max_length=50),
                ),
                ("cantidad_sesiones", models.PositiveIntegerField(default=1)),
                ("precio_sugerido", models.FloatField(default=10000)),
                ("email", models.EmailField(default="email@mail.com", max_length=50)),
                ("fecha", models.DateField(auto_now=True)),
            ],
        ),
    ]
